name: Deploy .NET 9 Web API to Azure

on:
  push:
    branches:
      - master   # triggers on master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore CASH.FLOW.TRACKER.API/CASH.FLOW.TRACKER.API.csproj

    - name: Build
      run: dotnet build CASH.FLOW.TRACKER.API/CASH.FLOW.TRACKER.API.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish CASH.FLOW.TRACKER.API/CASH.FLOW.TRACKER.API.csproj -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: cashflowtracker          # must match your App Service name
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
